### PR TITLE
Elections

### PR DESCRIPTION
**Pull request by christopherkenny**
adv/arv + ndv/nrv names now present

### CODE REVIEW

**Comment by CoryMcCartan** [comment]
Needs to fix merge conflict but looks good to go to me

**Comment by christopherkenny** [comment]
Do you know if reverting the revert fix it or do I need to manually fix it?

**Comment by CoryMcCartan** [comment]
manual, I think, though there should be an easy command to have it take
your version of all the data files

**Comment by christopherkenny** [comment]
@CoryMcCartan I do not have write access to this repo currently

**Pull request merged**
